substitutions:
  devicename: 2gang-switch
  friendlyname: 2gang-switch

esphome:
  name: $devicename
  friendly_name: $friendlyname

bk72xx:
  board: generic-bk7231n-qfn32-tuya
  framework:
    version: latest

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "EEqyzbozylQ3keP5aIUCroeuI92J4pEQHvf2/hwWVtw="

ota:
  - platform: esphome
    password: "21cdd4f88e1d39eaa75af128f2976a97"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "2G-Beken Fallback Hotspot"
    password: wacEfa33av34a

captive_portal:


sensor:
  - platform: uptime
    name: $friendlyname Uptime
    update_interval: 60s

switch:
  - platform: gpio
    name: $devicename Switch 1
    pin: GPIO7
    id: relay_1

  - platform: gpio
    name: $devicename Switch 2
    pin: GPIO9
    id: relay_2

binary_sensor:
  - platform: status
    name: $devicename Status

  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    name: $devicename Button 1
    on_press:
      - switch.toggle: relay_2

  - platform: gpio
    pin:
      number: GPIO24
      mode: INPUT_PULLUP
      inverted: True
    name: $devicename Button 2
    on_press:
      - switch.toggle: relay_1

status_led:
  pin:
    number: GPIO6
    inverted: False